### ISSUE TITLE
Plugin not compatibile with Java 1.8

### ISSUE THREAD

**Issue by grzegorz7** [jenkinsci/scm-sync-configuration-plugin#24]
When I try to compile project (0.0.8) with maven based on Java 1.8 i get following error:
```
[INFO] --- maven-hpi-plugin:1.67:apt-compile (default-apt-compile) @ scm-sync-configuration ---
[WARNING] Error injecting: org.jenkinsci.maven.plugins.hpi.AptCompiler
java.lang.NoClassDefFoundError: com/sun/mirror/apt/AnnotationProcessorFactory
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2658)
	at java.lang.Class.getDeclaredConstructors(Class.java:2007)
```

**Comment by rodrigc** [comment]
Fixed in https://github.com/jenkinsci/scm-sync-configuration-plugin/commit/0d67ed2055af05fdcb5eaebac3783c5e4614e0fb
